### ISSUE TITLE
Valid URL is failing.

### ISSUE THREAD

**Issue by texaspacm** [boblauer/url-exists#3]
Hello,

When I run this URL:  https://www.rent-river-oaks.com/
It's flagging it as invalid.  But the URL is working just fine. 

```
var urlExists = require("url-exists")

urlExists('https://www.rent-river-oaks.com', function(err, exists) {
  console.log(exists); // true
});
```

Thanks,

**Comment by boblauer** [comment]
It looks like `https://www.rent-river-oaks.com` returns a 400 on HEAD requests, which is why `exists` is coming back as `false`.

I'm not sure what the best way to proceed is.  As the code is written, any 4xx response status code is considered to be a failure.

**Comment by texaspacm** [comment]
Yep.  I tried this using the REQUEST module and it's still 400 status code.

It's strange b/c the website is loading just fine in the browser.

**Comment by boblauer** [comment]
The difference is the browser does a GET request, where as this package does a HEAD request.  The reason I do a HEAD request is because I want the response to be as small as possible.  I don't want to have to read an entire webpage into memory just to determine if it exists.

**Comment by ambrosiora** [comment]
Hi, @boblauer I think I can help to solve.
I already solved or "workarounded" on my code.

the https://www.rent-river-oaks.com/ is now recognized as online
and the https://amazon.com mentioned on https://github.com/boblauer/url-exists/issues/6 too

I think we don't have to trust only on HEAD method, because there's a lot of poor implemented or maybe a kind of "over-secured" websites that dont respond to HEAD methods, or respond with wrong response codes, giving us a false positive.

Look, I'm using your library and when the urlExists response is `true` I assume that the url is online.

But when your library give me a urlExists `false`, I also make another check with a traditional "GET" method and check the status code.

If is real offline, the get method will have no impact on load an entire webpage into memory, as you mentioned above...
If is online, unfortunately, due to wrong head response, there will be a little resource usage, but I think that it's better than have a false positive.

What do you think?

here's a code snippet that I made the workaround.
```
// on node.js I need to install node-fetch...
// npm install node-fetch --save

const fetch = require('node-fetch');

urlExists(url, function(err, exists) {
  if (exists) {
    console.log('ONLINE!');
    return;
  }

  // did not returned above, so... try do a normal "get" request and check status
  fetch(new URL(url))
    .then(response => {
      const realResult = /4\d\d/.test(response.status) === false   //using the same regex you use, to test the response status
      console.log(realResult);
    })
    .catch(err => {
      //maybe you have to handle this error, just returning as "false"
      console.log(err);
    });
});
```


**I hope you can use part of this code and add to the core of your library, which would be a nice accuracy improvement.**
